# Generated by Django 4.1.7 on 2023-05-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('vreve_descripcion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField(default=20)),
            ],
        ),
    ]
