# Generated by Django 4.1.7 on 2023-06-26 20:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('cel', models.CharField(max_length=15)),
                ('tel', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('trabajo', models.CharField(blank=True, max_length=30, null=True)),
                ('nota', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('contactos', models.ManyToManyField(blank=True, to='contactos.contacto')),
            ],
        ),
    ]
