# Generated by Django 4.1.7 on 2023-05-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salario',
            old_name='Trabajo',
            new_name='trabajo',
        ),
    ]
