# Generated by Django 4.1.7 on 2023-05-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_rename_trabajo_salario_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
