# Generated by Django 4.1.7 on 2023-05-05 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_anual', models.IntegerField(default=10000, max_length=10)),
                ('extra_junio', models.BooleanField(default=True)),
                ('extra_nobiembre', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripsion', models.TextField(max_length=200)),
                ('salario', models.ManyToManyField(to='empleados.salario')),
            ],
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('departamento', models.ManyToManyField(to='empleados.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('ci', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('local', models.ManyToManyField(to='empleados.local')),
                ('trabajo', models.ManyToManyField(to='empleados.trabajo')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='ciudad',
            field=models.ManyToManyField(to='empleados.pais'),
        ),
    ]
