# Generated by Django 4.1.7 on 2023-04-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comments_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='asignatura',
            field=models.CharField(default='Fiema', max_length=100),
        ),
    ]
