# Generated by Django 4.1.7 on 2023-04-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0004_rename_comments_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='coment',
            new_name='comment',
        ),
    ]
